site_name: Awakening TTRPG Web-SRD
dev_addr: 0.0.0.0:8000

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: ru
#    - mkpdfs

markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2

theme:
  name: readthedocs
  custom_dir: css/

extra_css:
   - main.css
